# Generated by Django 5.1.1 on 2024-10-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='vinylrecord',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='vinylrecord',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тега (максимум 50 символов)', max_length=50, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='vinylrecord',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='vinylrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='vinylrecord',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='records', to='vinyls.tag'),
        ),
        migrations.AlterField(
            model_name='vinylrecord',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название альбома'),
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='vinyl_audio/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('vinyl_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='vinyls.vinylrecord')),
            ],
        ),
    ]
